version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ${BACKEND_CONTAINER_NAME}_be
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://prisma:prisma@postgres:5432/${DB_NAME}

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres-data: