version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ${BACKEND_CONTAINER_NAME}_be
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@localhost:5432?schema=public

  db:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres-data: